name: Publish binary

on:
  push:
    branches: 
      master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo        
        uses: actions/checkout@v2

      - name: Install necessary software
        run: |
          apt-get update && \
          apt-get -y --no-install-recommends install \
          cmake \
          make \
          clang \
          g++ \
          curl \
          default-jdk \
          python3 \
          python3-setuptools \
          python-is-python3 \
          sudo

      - name: Configure
        run: |
          python scripts/mk_make.py

      - name: Build
        run: |
          cd build && make && sudo make install

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: z3-executable
          path: build/z3
